import fs from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { createInterface } from "node:readline";
import { loadSecrets, getGitContext } from "@bantay/core";
import { exec } from "node:child_process";
import { execSync } from "node:child_process";

/**
 * Executes the bantay init command
 */
export async function initCommand(directory: string) {
  if (directory) {
    await fs.mkdir(directory, { recursive: true });
    process.chdir(directory);
  }

  // 0. Login Check
  try {
    const secrets = await loadSecrets();
    if (!process.env.BANTAY_AUTH0_CLIENT_SECRET && !secrets.BANTAY_AUTH0_CLIENT_SECRET) {
      throw new Error();
    }
  } catch (e) {
    if (!process.env.BANTAY_AUTH0_CLIENT_SECRET) {
      console.error(chalk.red("❌ Not logged in. Run 'bantay login' first."));
      process.exit(1);
    }
  }

  const projectRoot = process.cwd();
  const gitCtx = getGitContext();

  // 1. Check if we are in a git repo
  if (!gitCtx.isRepo) {
    console.warn(chalk.yellow("⚠️  No .git found. Initializing git repo..."));
    execSync("git init", { cwd: projectRoot });
    console.log(chalk.green("✅ Git repo initialized."));
  }

  const gitDir = path.join(projectRoot, ".git");

  console.log(chalk.blue("🛡️  Initializing Bantay..."));

  // 2. Create default .bantay.yaml if not exists
  const configPath = path.join(projectRoot, ".bantay.yaml");
  try {
    await fs.access(configPath);
    console.log(chalk.dim("- .bantay.yaml already exists. Skipping."));
  } catch (e) {
    const defaultConfig = `# Bantay Configuration
# Repo-level policy overrides global defaults in ~/.bantay/config

ntfy:
  topic: "bantay-repolog"
  # url and auth are loaded from BANTAY_NTFY_URL, BANTAY_NTFY_USERNAME etc.

scan:
  sensitiveFiles:
    - "*.pem"
    - "*.key"
    - ".env"
    - "id_rsa"
    - "*.pfx"
    - "*.map"
  sourceMaps:
    publicRepo: "high"
    privateRepo: "medium"
  blockOnTimeout: true
  cibaTimeoutSeconds: 60

git:
  protectedBranches: ["main", "master", "prod"]

thresholds:
  highRiskLineCount: 1000
`;
    await fs.writeFile(configPath, defaultConfig);
    console.log(chalk.green("✅ Created default .bantay.yaml"));
  }

  // 3. Install pre-push hook
  const hooksDir = path.join(gitDir, "hooks");
  const prePushPath = path.join(hooksDir, "pre-push");

  const hookContent = `#!/bin/sh
# Bantay Pre-Push Hook
# Automatically generated by bantay init

echo "🛡️  Bantay: Checking for secrets before push..."

# Run the scan command
bantay scan --pre-push
EXIT_CODE=$?

exit $EXIT_CODE
`;

  // Check if hook already exists
  if (existsSync(prePushPath)) {
    const existing = readFileSync(prePushPath, "utf8");
    if (existing.includes("Bantay")) {
      console.log(chalk.dim("- Bantay hook already installed. Overwriting with latest version."));
    } else {
      // Third-party hook exists - ask user
      const rl = createInterface({ input: process.stdin, output: process.stdout });
      process.stdin.resume();

      const answer = await new Promise<string>((resolve) => {
        const question = chalk.yellow(
          "⚠️  A pre-push hook already exists. [o]verwrite, [m]erge (append Bantay), or [s]kip? "
        );
        process.stderr.write(question);
        rl.question("", resolve);
      });
      rl.close();

      if (answer.toLowerCase() === "s") {
        console.log(chalk.yellow("⏭️  Skipping hook installation."));
      } else if (answer.toLowerCase() === "m") {
        // Append bantay call to existing hook
        const mergeContent = `\n\n# Bantay Security Scan\nREPO_ROOT=$(git rev-parse --show-toplevel)\nnode "$REPO_ROOT/packages/cli/dist/index.js" scan || exit 1\n`;
        await fs.appendFile(prePushPath, mergeContent);
        console.log(chalk.green("✅ Bantay appended to existing pre-push hook."));
        console.log(chalk.bold.green("\n🎉 Bantay is now active! Your pushes are protected.\n"));
        return;
      }
      // else overwrite - fall through
    }
  }

  try {
    await fs.writeFile(prePushPath, hookContent);
    await fs.chmod(prePushPath, "755"); // Make executable
    console.log(chalk.green("✅ Installed pre-push hook at .git/hooks/pre-push"));
  } catch (error) {
    console.error(
      chalk.red(`Failed to install hook: ${error instanceof Error ? error.message : String(error)}`)
    );
    process.exit(1);
  }

  console.log(chalk.bold.green(`\n🎉 Bantay is now active! Your pushes are protected.`));
  if (directory) {
    console.log(`To continue, run \`cd ${directory}\``);
  }
}
