import fs from "node:fs/promises";
import path from "node:path";
import chalk from "chalk";
import { execSync } from "node:child_process";

/**
 * Executes the bantay init command
 */
export async function initCommand() {
  const projectRoot = process.cwd();
  const gitDir = path.join(projectRoot, ".git");

  // 1. Check if we are in a git repo
  try {
    await fs.access(gitDir);
  } catch (e) {
    console.error(chalk.red("Error: .git directory not found. Please run this command from the root of a git repository."));
    process.exit(1);
  }

  console.log(chalk.blue("🛡️  Initalizing Bantay..."));

  // 2. Create default .bantay.yaml if not exists
  const configPath = path.join(projectRoot, ".bantay.yaml");
  try {
    await fs.access(configPath);
    console.log(chalk.dim("- .bantay.yaml already exists. Skipping."));
  } catch (e) {
    const defaultConfig = `# Bantay Configuration
# Copy .env.example to .env and fill in secrets before running bantay init

ntfy:
  topic: "hackathon-test"
  # url and auth are loaded from NTFY_URL, NTFY_USERNAME, NTFY_PASSWORD env vars

auth0:
  # domain and clientId are loaded from AUTH0_DOMAIN, AUTH0_CLIENT_ID env vars

git:
  protectedBranches: ["main", "master", "prod"]

thresholds:
  highRiskLineCount: 1000  # PRD spec: chungus commit threshold
`;
    await fs.writeFile(configPath, defaultConfig);
    console.log(chalk.green("✅ Created default .bantay.yaml"));
  }

  // 3. Install pre-push hook
  const hooksDir = path.join(gitDir, "hooks");
  const prePushPath = path.join(hooksDir, "pre-push");

  const hookContent = `#!/bin/sh
# Bantay Pre-Push Hook
# Automatically generated by bantay init

echo "🛡️  Bantay: Checking for secrets before push..."

# Run the scan command using the relative path from repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
node "$REPO_ROOT/packages/cli/dist/index.ts" scan

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ Push blocked by Bantay. Please review the security findings above."
  exit 1
fi

exit 0
`;

  try {
    await fs.writeFile(prePushPath, hookContent);
    await fs.chmod(prePushPath, "755"); // Make executable
    console.log(chalk.green("✅ Installed pre-push hook at .git/hooks/pre-push"));
  } catch (error) {
    console.error(chalk.red(`Failed to install hook: ${error instanceof Error ? error.message : String(error)}`));
    process.exit(1);
  }

  console.log(chalk.bold.green("\n🎉 Bantay is now active! Your pushes are protected.\n"));
}
